"""Generate a deterministic, ISO-aligned metadata tree for an OSWM node.

The generator deliberately leaves ``data/`` untouched.  It mirrors every data
directory below the sibling ``metadata/`` directory, writes one collection
record as ``index.json`` in each mirrored directory, and writes a JSON sidecar
for every non-index data file.

This is an OSWM JSON application profile.  It aligns its concepts with the ISO
standards listed in :data:`ALIGNED_STANDARDS`; it is not the XML encoding
defined by ISO 19115-3.
"""

from __future__ import annotations

import argparse
import hashlib
import importlib.util
import json
import mimetypes
import os
import re
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path, PurePosixPath
from typing import Any, Iterable

try:
    from zoneinfo import ZoneInfo
except ImportError:  # pragma: no cover - Python 3.9+ is used by OSWM
    ZoneInfo = None  # type: ignore[assignment]


PROFILE_VERSION = "1.0.0"
GENERATOR_ID = "oswm_codebase.metadata.metadata_generation"
SCHEMA_URL = (
    "https://raw.githubusercontent.com/kauevestena/oswm_codebase/main/"
    "metadata/schemas/oswm-metadata.schema.json"
)

ALIGNED_STANDARDS = [
    {
        "name": "ISO 15836-1:2017",
        "role": "cross-domain resource description",
        "url": "https://www.iso.org/standard/71339.html",
    },
    {
        "name": "ISO 19115-1:2014",
        "role": "geographic metadata fundamentals",
        "url": "https://www.iso.org/standard/53798.html",
    },
    {
        "name": "ISO 19115-2:2019",
        "role": "acquisition and processing lineage",
        "url": "https://www.iso.org/standard/67039.html",
    },
    {
        "name": "ISO 19157-1:2023",
        "role": "geographic data quality reporting",
        "url": "https://www.iso.org/standard/78900.html",
    },
    {
        "name": "ISO 19110:2016",
        "role": "feature catalogue concepts where applicable",
        "url": "https://www.iso.org/standard/57303.html",
    },
]

FOLDER_PROFILES: dict[str, dict[str, Any]] = {
    "boundaries": {
        "title": "Study-area boundaries",
        "abstract": "Boundary geometry and descriptive information for the node coverage area.",
        "process": "The node boundary is resolved from the configured place or bounding box.",
        "sources": ["OpenStreetMap and Nominatim"],
    },
    "processed": {
        "title": "Processed pedestrian-network data",
        "abstract": "Cleaned and structured pedestrian-network layers prepared by OSWM.",
        "process": "Derived from the node's raw OpenStreetMap extracts using OSWM filtering and normalization rules.",
        "sources": ["OpenStreetMap", "data/raw"],
    },
    "raw": {
        "title": "Raw pedestrian-network data",
        "abstract": "Unfiltered pedestrian-network extracts acquired for the configured node area.",
        "process": "Acquired from OpenStreetMap-compatible services for the configured node coverage.",
        "sources": ["OpenStreetMap", "ohsome API"],
    },
    "tiles": {
        "title": "Pedestrian-network vector tiles",
        "abstract": "PMTiles packages generated for efficient static web-map delivery.",
        "process": "Derived from processed OSWM pedestrian-network layers.",
        "sources": ["data/processed"],
    },
    "updates": {
        "title": "Update and version history",
        "abstract": "Refresh status, OSM changeset monitoring, and feature-version history.",
        "process": "Generated from node workflow executions and OpenStreetMap history services.",
        "sources": ["OpenStreetMap", "ohsome API", "OSWM workflows"],
    },
    "vrts": {
        "title": "Virtual dataset descriptors",
        "abstract": "GDAL VRT descriptors that group and expose OSWM datasets.",
        "process": "Generated from the available node data distributions.",
        "sources": ["data/processed", "data/raw", "data/tiles"],
    },
    "data_quality": {
        "title": "Data-quality findings",
        "abstract": "Spatial outputs identifying potential topology, geometry, or tagging inconsistencies.",
        "process": "Generated by OSWM validation rules and quality-analysis routines.",
        "sources": ["data/raw", "data/processed", "OSWM validation rules"],
    },
    "routing": {
        "title": "Accessible-routing products",
        "abstract": "Routing network, profiles, grades, and generation provenance for pedestrian routing.",
        "process": (
            "Derived from processed pedestrian data, explicit OSM incline evidence, "
            "and configured terrain context."
        ),
        "sources": ["data/processed", "OpenStreetMap incline tags", "Copernicus DEM"],
    },
    "hazard_analysis": {
        "title": "Pedestrian hazard-analysis products",
        "abstract": "Profile-specific hazard evidence, rules, tiles, and terrain-context products.",
        "process": "Derived from OSWM pedestrian features, accessibility rules, and configured terrain context.",
        "sources": ["data/processed", "OpenStreetMap", "Copernicus DEM"],
    },
    "snapshots": {
        "title": "Web-map analytical summaries",
        "abstract": "Precomputed summaries used by OSWM web-map charts and printable snapshots.",
        "process": "Derived from the published pedestrian-network layers and web-map themes.",
        "sources": ["data/processed", "OSWM web-map configuration"],
    },
}

MEDIA_TYPES = {
    ".geojson": ("application/geo+json", "GeoJSON"),
    ".parquet": ("application/vnd.apache.parquet", "GeoParquet"),
    ".pmtiles": ("application/vnd.pmtiles", "PMTiles"),
    ".vrt": ("application/xml", "GDAL VRT"),
    ".json": ("application/json", "JSON"),
    ".html": ("text/html", "HTML"),
    ".png": ("image/png", "PNG"),
    ".csv": ("text/csv", "CSV"),
    ".txt": ("text/plain", "Text"),
}

GEOGRAPHIC_SUFFIXES = {
    ".fgb",
    ".geojson",
    ".gml",
    ".gpkg",
    ".kml",
    ".mbtiles",
    ".parquet",
    ".pmtiles",
    ".shp",
    ".tif",
    ".tiff",
    ".vrt",
}
FEATURE_SUFFIXES = {
    ".fgb",
    ".geojson",
    ".gml",
    ".gpkg",
    ".kml",
    ".parquet",
    ".pmtiles",
    ".shp",
}


def metadata_relative_path_for_data(data_path: str | Path) -> str:
    """Return the deterministic metadata path for a path below ``data/``.

    Directory manifests named ``index.json`` map directly to the mirrored
    collection record.  Other files retain their complete filename and gain a
    ``.metadata.json`` suffix, preventing collisions between equal stems with
    different formats.
    """

    normalized = str(data_path).replace("\\", "/").lstrip("./")
    pure = PurePosixPath(normalized)
    if not pure.parts or pure.parts[0] != "data":
        raise ValueError(f"Expected a path below data/: {data_path}")

    relative = PurePosixPath(*pure.parts[1:])
    if relative.name == "index.json":
        return str(PurePosixPath("metadata") / relative)
    return str(
        PurePosixPath("metadata")
        / relative.parent
        / f"{relative.name}.metadata.json"
    )


def _load_json(path: Path, default: Any) -> Any:
    try:
        with path.open("r", encoding="utf-8") as handle:
            return json.load(handle)
    except (OSError, ValueError, TypeError):
        return default


def _atomic_json_dump(payload: dict[str, Any], path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    temporary = path.with_name(f".{path.name}.tmp")
    with temporary.open("w", encoding="utf-8") as handle:
        json.dump(payload, handle, indent=2, ensure_ascii=False)
        handle.write("\n")
    os.replace(temporary, path)


def _load_node_config(node_root: Path) -> Any:
    config_path = node_root / "config.py"
    if not config_path.exists():
        raise FileNotFoundError(f"OSWM node config not found: {config_path}")

    module_name = f"oswm_node_config_{hash(config_path.resolve())}"
    spec = importlib.util.spec_from_file_location(module_name, config_path)
    if spec is None or spec.loader is None:
        raise RuntimeError(f"Could not load OSWM node config: {config_path}")
    module = importlib.util.module_from_spec(spec)
    sys.path.insert(0, str(node_root))
    try:
        spec.loader.exec_module(module)
    finally:
        try:
            sys.path.remove(str(node_root))
        except ValueError:
            pass
    return module


def _node_context(node_root: Path) -> dict[str, Any]:
    config = _load_node_config(node_root)
    city = str(getattr(config, "CITY_NAME", node_root.name))
    username = str(getattr(config, "USERNAME", "unknown"))
    repository = str(getattr(config, "REPO_NAME", node_root.name))
    language = str(getattr(config, "METADATA_LANGUAGE", "en"))
    base_url = str(
        getattr(
            config,
            "NODE_BASE_URL",
            f"https://{username}.github.io/{repository}/",
        )
    ).rstrip("/") + "/"
    timezone_name = str(getattr(config, "METADATA_TIMEZONE", "UTC"))

    return {
        "city": city,
        "username": username,
        "repository": repository,
        "language": language,
        "base_url": base_url,
        "timezone": timezone_name,
        "repository_url": f"https://github.com/{username}/{repository}",
    }


def _profile(domain: str, include_feature_catalogue: bool) -> dict[str, Any]:
    aligned_with = [ALIGNED_STANDARDS[0]]
    if domain in {"geographic", "mixed"}:
        aligned_with.extend(ALIGNED_STANDARDS[1:4])
        if include_feature_catalogue:
            aligned_with.append(ALIGNED_STANDARDS[4])

    return {
        "name": "OSWM Metadata Profile",
        "version": PROFILE_VERSION,
        "encoding": "application/json",
        "alignment": "conceptual",
        "domain": domain,
        "aligned_with": aligned_with,
        "conformance_note": (
            "This is an OSWM JSON application profile. Geographic ISO concepts "
            "are applied only to geographic or mixed resources; the profile does "
            "not claim conformance to the ISO 19115-3 XML encoding."
        ),
    }


def _codebase_revision() -> dict[str, str | None]:
    codebase_root = Path(__file__).resolve().parents[1]

    def git_value(*args: str) -> str | None:
        try:
            result = subprocess.run(
                ["git", *args],
                cwd=codebase_root,
                check=True,
                capture_output=True,
                text=True,
                timeout=10,
            )
        except (OSError, subprocess.SubprocessError):
            return None
        value = result.stdout.strip()
        return value or None

    return {
        "repository": "https://github.com/kauevestena/oswm_codebase",
        "commit": git_value("rev-parse", "HEAD"),
        "commit_date": git_value("show", "-s", "--format=%cI", "HEAD"),
    }


def _parse_registry_timestamp(node_root: Path, timezone_name: str) -> tuple[str | None, dict[str, Any]]:
    registry = _load_json(node_root / "data" / "updates" / "registry.json", {})
    if not isinstance(registry, dict):
        return None, {}

    tz = timezone.utc
    if ZoneInfo is not None:
        try:
            tz = ZoneInfo(timezone_name)
        except (KeyError, ValueError):
            tz = timezone.utc

    parsed: list[datetime] = []
    for value in registry.values():
        if not isinstance(value, str):
            continue
        for pattern in ("%d/%m/%Y %H:%M:%S", "%Y-%m-%dT%H:%M:%S%z"):
            try:
                candidate = datetime.strptime(value, pattern)
                if candidate.tzinfo is None:
                    candidate = candidate.replace(tzinfo=tz)
                parsed.append(candidate)
                break
            except ValueError:
                continue

    updated = max(parsed).isoformat() if parsed else None
    return updated, registry


def _boundary_spatial(node_root: Path, base_url: str) -> dict[str, Any] | None:
    info = _load_json(node_root / "data" / "boundaries" / "infos.json", {})
    bbox = info.get("bbox") if isinstance(info, dict) else None
    if not (
        isinstance(bbox, list)
        and len(bbox) == 4
        and all(isinstance(value, (int, float)) for value in bbox)
    ):
        return None
    spatial = {
        "scope": "node_coverage",
        "bbox": bbox,
        "bbox_order": ["west", "south", "east", "north"],
        "reference_system": "http://www.opengis.net/def/crs/OGC/1.3/CRS84",
    }
    if (node_root / "data" / "boundaries" / "polygon.geojson").is_file():
        spatial["geometry"] = f"{base_url}data/boundaries/polygon.geojson"
    return spatial


def _responsible_parties(context: dict[str, Any]) -> list[dict[str, str]]:
    return [
        {
            "name": context["username"],
            "role": "pointOfContact",
            "url": f"https://github.com/{context['username']}",
        },
        {
            "name": "OpenSidewalkMap",
            "role": "publisher",
            "url": context["repository_url"],
        },
    ]


def _folder_profile(relative: PurePosixPath) -> dict[str, Any]:
    if not relative.parts:
        return {
            "title": "Node data",
            "abstract": "Published data products provided by this OSWM node.",
            "process": "Generated or collected by the OSWM node pipeline.",
            "sources": ["OSWM node pipeline"],
        }

    key = relative.parts[0] if relative.parts else "data"
    default_title = _humanize(key)
    return FOLDER_PROFILES.get(
        key,
        {
            "title": default_title,
            "abstract": f"Published data products stored below data/{key}.",
            "process": "Generated or collected by the OSWM node pipeline.",
            "sources": ["OSWM node pipeline"],
        },
    )


def _humanize(value: str) -> str:
    value = re.sub(r"\.(metadata\.)?json$", "", value, flags=re.IGNORECASE)
    value = re.sub(r"\.(geojson|parquet|pmtiles|vrt|png|html|csv|txt)$", "", value, flags=re.IGNORECASE)
    return value.replace("_", " ").replace("-", " ").strip().title()


def _media_type(path: Path) -> tuple[str, str]:
    known = MEDIA_TYPES.get(path.suffix.lower())
    if known:
        return known
    guessed, _ = mimetypes.guess_type(path.name)
    return guessed or "application/octet-stream", path.suffix.lstrip(".").upper() or "Binary"


def _resource_type(path: Path) -> str:
    suffix = path.suffix.lower()
    name = path.name.lower()
    if suffix in {".geojson", ".parquet"}:
        return "dataset"
    if suffix == ".pmtiles":
        return "tileset"
    if suffix == ".vrt":
        return "dataset-description"
    if suffix == ".png":
        return "image"
    if suffix == ".html":
        return "document"
    if "report" in name or name in {"metadata.json", "terrain.json"}:
        return "report"
    if "profiles" in name or "rules" in name:
        return "model-configuration"
    if "cache" in name:
        return "cache"
    return "dataset"


def _resource_domain(path: Path, data_root: Path) -> tuple[str, bool]:
    """Return the standards domain and feature-catalogue applicability."""

    relative = path.relative_to(data_root)
    suffix = path.suffix.lower()
    geographic = suffix in GEOGRAPHIC_SUFFIXES
    if relative.parts and relative.parts[0] == "boundaries":
        geographic = True
    if relative.parts[:2] == ("updates", "versioning"):
        geographic = True
    if suffix == ".png" and path.stem.startswith("terrain_"):
        geographic = True
    return ("geographic" if geographic else "non-geographic", suffix in FEATURE_SUFFIXES)


def _collection_domain(directory: Path, data_root: Path) -> tuple[str, bool]:
    domains: set[str] = set()
    include_feature_catalogue = False
    for path in _iter_data_files(directory):
        domain, is_feature_resource = _resource_domain(path, data_root)
        domains.add(domain)
        include_feature_catalogue = include_feature_catalogue or is_feature_resource

    if len(domains) > 1:
        return "mixed", include_feature_catalogue
    if domains:
        return next(iter(domains)), include_feature_catalogue
    return "non-geographic", False


def _sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def _quality(base_url: str, profile_domain: str) -> dict[str, Any]:
    if profile_domain == "non-geographic":
        return {
            "scope": "resource",
            "standard": "OSWM Metadata Profile 1.0",
            "statement": (
                "The record reports provenance and technical integrity without "
                "asserting a universal fitness-for-use threshold."
            ),
            "related_report": f"{base_url}quality_check/index.json",
        }

    return {
        "scope": "resource",
        "standard": "ISO 19157-1:2023",
        "statement": (
            "The record reports provenance and technical integrity. It does not "
            "assert a universal fitness-for-use threshold."
        ),
        "related_report": f"{base_url}quality_check/index.json",
    }


def _generation_info(updated: str | None, revision: dict[str, Any]) -> dict[str, Any]:
    generated_at = updated or revision.get("commit_date")
    return {
        "generator": GENERATOR_ID,
        "profile_version": PROFILE_VERSION,
        "generated_at": generated_at,
        "code": revision,
        "source_root": "data",
        "deterministic": True,
    }


def _base_record(
    *,
    context: dict[str, Any],
    identifier: str,
    resource_type: str,
    title: str,
    abstract: str,
    spatial: dict[str, Any] | None,
    updated: str | None,
    registry: dict[str, Any],
    lineage: dict[str, Any],
    revision: dict[str, Any],
    profile_domain: str,
    include_feature_catalogue: bool,
) -> dict[str, Any]:
    return {
        "$schema": SCHEMA_URL,
        "metadata_profile": _profile(profile_domain, include_feature_catalogue),
        "identifier": identifier,
        "resource_type": resource_type,
        "title": title,
        "abstract": abstract,
        "language": context["language"],
        "responsible_parties": _responsible_parties(context),
        "spatial": spatial,
        "temporal": {
            "updated": updated,
            "node_registry": registry,
        },
        "lineage": lineage,
        "quality": _quality(context["base_url"], profile_domain),
        "rights": {
            "statement": (
                "Licensing and attribution follow the upstream sources and the "
                "specific distribution being described."
            )
        },
        "metadata_generation": _generation_info(updated, revision),
    }


def _iter_data_directories(data_root: Path) -> Iterable[Path]:
    yield data_root
    for path in sorted(data_root.rglob("*"), key=lambda item: item.as_posix()):
        if path.is_dir() and not any(part.startswith(".") for part in path.relative_to(data_root).parts):
            yield path


def _iter_data_files(data_root: Path) -> Iterable[Path]:
    for path in sorted(data_root.rglob("*"), key=lambda item: item.as_posix()):
        if not path.is_file():
            continue
        relative = path.relative_to(data_root)
        if any(part.startswith(".") for part in relative.parts):
            continue
        if path.name == "index.json" or path.name.endswith(".tmp"):
            continue
        yield path


def _metadata_path_for_file(path: Path, data_root: Path, metadata_root: Path) -> Path:
    relative = path.relative_to(data_root)
    return metadata_root / relative.parent / f"{relative.name}.metadata.json"


def _collection_metadata_path(directory: Path, data_root: Path, metadata_root: Path) -> Path:
    relative = directory.relative_to(data_root)
    return metadata_root / relative / "index.json"


def _file_record(
    path: Path,
    *,
    data_root: Path,
    metadata_root: Path,
    context: dict[str, Any],
    spatial: dict[str, Any] | None,
    updated: str | None,
    registry: dict[str, Any],
    revision: dict[str, Any],
    calculate_checksums: bool,
) -> tuple[Path, dict[str, Any]]:
    relative = path.relative_to(data_root)
    relative_posix = PurePosixPath(relative.as_posix())
    data_rel = PurePosixPath("data") / relative_posix
    metadata_path = _metadata_path_for_file(path, data_root, metadata_root)
    metadata_rel = metadata_path.relative_to(metadata_root.parent).as_posix()
    profile = _folder_profile(relative_posix)
    media_type, format_name = _media_type(path)
    checksum = _sha256(path) if calculate_checksums else None
    profile_domain, include_feature_catalogue = _resource_domain(path, data_root)

    title = f"{context['city']} — {_humanize(path.name)}"
    abstract = (
        f"{profile['abstract']} This record describes the {format_name} "
        f"distribution at {data_rel.as_posix()}."
    )
    record = _base_record(
        context=context,
        identifier=f"{context['base_url']}{metadata_rel}",
        resource_type=_resource_type(path),
        title=title,
        abstract=abstract,
        spatial=spatial if profile_domain == "geographic" else None,
        updated=updated,
        registry=registry,
        lineage={
            "process_description": profile["process"],
            "sources": profile["sources"],
        },
        revision=revision,
        profile_domain=profile_domain,
        include_feature_catalogue=include_feature_catalogue,
    )
    distribution: dict[str, Any] = {
        "resource_path": data_rel.as_posix(),
        "access_url": f"{context['base_url']}{data_rel.as_posix()}",
        "download_url": f"{context['base_url']}{data_rel.as_posix()}",
        "media_type": media_type,
        "format": format_name,
        "byte_size": path.stat().st_size,
    }
    if checksum is not None:
        distribution["checksum"] = {
            "algorithm": "SHA-256",
            "value": checksum,
        }
    record["distribution"] = distribution
    record["links"] = [
        {"rel": "self", "href": f"{context['base_url']}{metadata_rel}", "type": "application/json"},
        {"rel": "describes", "href": distribution["access_url"], "type": media_type},
        {
            "rel": "collection",
            "href": (
                f"{context['base_url']}"
                f"{metadata_path.parent.relative_to(metadata_root.parent).as_posix()}"
                "/index.json"
            ),
            "type": "application/json",
        },
    ]
    return metadata_path, record


def _collection_record(
    directory: Path,
    *,
    data_root: Path,
    metadata_root: Path,
    context: dict[str, Any],
    spatial: dict[str, Any] | None,
    updated: str | None,
    registry: dict[str, Any],
    revision: dict[str, Any],
    calculate_checksums: bool,
) -> tuple[Path, dict[str, Any]]:
    relative = directory.relative_to(data_root)
    relative_posix = PurePosixPath(relative.as_posix()) if relative.parts else PurePosixPath()
    metadata_path = _collection_metadata_path(directory, data_root, metadata_root)
    metadata_rel = metadata_path.relative_to(metadata_root.parent).as_posix()
    data_rel = PurePosixPath("data") / relative_posix
    profile = _folder_profile(relative_posix)
    collection_title = profile["title"]
    profile_domain, include_feature_catalogue = _collection_domain(directory, data_root)
    if relative.parts[1:]:
        collection_title = f"{collection_title} — {_humanize(relative.name)}"

    record = _base_record(
        context=context,
        identifier=f"{context['base_url']}{metadata_rel}",
        resource_type="catalog" if not relative.parts else "collection",
        title=f"{context['city']} — {collection_title}",
        abstract=(
            f"{profile['abstract']} This collection mirrors {data_rel.as_posix()} "
            "without changing the source data directory."
        ),
        spatial=spatial if profile_domain in {"geographic", "mixed"} else None,
        updated=updated,
        registry=registry,
        lineage={
            "process_description": profile["process"],
            "sources": profile["sources"],
        },
        revision=revision,
        profile_domain=profile_domain,
        include_feature_catalogue=include_feature_catalogue,
    )

    assets: list[dict[str, Any]] = []
    for child in sorted(directory.iterdir(), key=lambda item: item.name):
        if (
            not child.is_file()
            or child.name.startswith(".")
            or child.name == "index.json"
            or child.name.endswith(".tmp")
        ):
            continue
        media_type, format_name = _media_type(child)
        data_child_rel = PurePosixPath("data") / PurePosixPath(child.relative_to(data_root).as_posix())
        child_metadata = _metadata_path_for_file(child, data_root, metadata_root)
        asset: dict[str, Any] = {
            "title": _humanize(child.name),
            "resource": f"{context['base_url']}{data_child_rel.as_posix()}",
            "metadata": f"{context['base_url']}{child_metadata.relative_to(metadata_root.parent).as_posix()}",
            "media_type": media_type,
            "format": format_name,
            "byte_size": child.stat().st_size,
        }
        if calculate_checksums:
            asset["checksum"] = {"algorithm": "SHA-256", "value": _sha256(child)}
        assets.append(asset)

    subcollections = []
    for child in sorted(directory.iterdir(), key=lambda item: item.name):
        if not child.is_dir() or child.name.startswith("."):
            continue
        child_metadata = _collection_metadata_path(child, data_root, metadata_root)
        subcollections.append(
            {
                "title": _humanize(child.name),
                "path": child_metadata.relative_to(metadata_root.parent).as_posix(),
                "href": f"{context['base_url']}{child_metadata.relative_to(metadata_root.parent).as_posix()}",
            }
        )

    record["assets"] = assets
    record["collections"] = subcollections
    record["links"] = [
        {"rel": "self", "href": f"{context['base_url']}{metadata_rel}", "type": "application/json"},
        {"rel": "describes", "href": f"{context['base_url']}{data_rel.as_posix()}/", "type": "text/html"},
    ]
    if relative.parts:
        parent_metadata = _collection_metadata_path(directory.parent, data_root, metadata_root)
        record["links"].append(
            {
                "rel": "collection",
                "href": f"{context['base_url']}{parent_metadata.relative_to(metadata_root.parent).as_posix()}",
                "type": "application/json",
            }
        )
    return metadata_path, record


def _is_generated_record(path: Path) -> bool:
    payload = _load_json(path, {})
    return (
        isinstance(payload, dict)
        and isinstance(payload.get("metadata_generation"), dict)
        and payload["metadata_generation"].get("generator") == GENERATOR_ID
    )


def _prune_stale_generated_records(metadata_root: Path, expected: set[Path]) -> list[str]:
    removed: list[str] = []
    if not metadata_root.exists():
        return removed
    for path in sorted(metadata_root.rglob("*.json"), reverse=True):
        if path in expected or not _is_generated_record(path):
            continue
        path.unlink()
        removed.append(path.relative_to(metadata_root.parent).as_posix())
    for directory in sorted(
        (path for path in metadata_root.rglob("*") if path.is_dir()),
        key=lambda item: len(item.parts),
        reverse=True,
    ):
        try:
            directory.rmdir()
        except OSError:
            pass
    return removed


def generate_metadata(
    node_root: str | Path = ".",
    *,
    calculate_checksums: bool = True,
    clean_stale: bool = True,
) -> dict[str, Any]:
    """Generate and validate the sibling metadata tree for one OSWM node."""

    root = Path(node_root).resolve()
    data_root = root / "data"
    metadata_root = root / "metadata"
    if not data_root.is_dir():
        raise FileNotFoundError(f"OSWM data directory not found: {data_root}")

    context = _node_context(root)
    revision = _codebase_revision()
    updated, registry = _parse_registry_timestamp(root, context["timezone"])
    spatial = _boundary_spatial(root, context["base_url"])
    expected: set[Path] = set()
    records_written = 0

    for data_file in _iter_data_files(data_root):
        target, record = _file_record(
            data_file,
            data_root=data_root,
            metadata_root=metadata_root,
            context=context,
            spatial=spatial,
            updated=updated,
            registry=registry,
            revision=revision,
            calculate_checksums=calculate_checksums,
        )
        _atomic_json_dump(record, target)
        expected.add(target)
        records_written += 1

    directories = list(_iter_data_directories(data_root))
    for directory in reversed(directories):
        target, record = _collection_record(
            directory,
            data_root=data_root,
            metadata_root=metadata_root,
            context=context,
            spatial=spatial,
            updated=updated,
            registry=registry,
            revision=revision,
            calculate_checksums=calculate_checksums,
        )
        if directory == data_root:
            record["integrity"] = {
                "data_files": sum(1 for _ in _iter_data_files(data_root)),
                "collections": len(directories) - 1,
                "generated_records": records_written + 1,
            }
        _atomic_json_dump(record, target)
        expected.add(target)
        records_written += 1

    removed = _prune_stale_generated_records(metadata_root, expected) if clean_stale else []
    errors = validate_metadata_tree(root, verify_checksums=False)
    if errors:
        raise RuntimeError("Metadata validation failed:\n- " + "\n- ".join(errors))

    return {
        "node_root": str(root),
        "metadata_root": str(metadata_root),
        "records_written": records_written,
        "stale_records_removed": removed,
        "checksums": calculate_checksums,
    }


def validate_metadata_tree(
    node_root: str | Path = ".",
    *,
    verify_checksums: bool = False,
) -> list[str]:
    """Return integrity errors for the generated node metadata tree."""

    root = Path(node_root).resolve()
    data_root = root / "data"
    metadata_root = root / "metadata"
    errors: list[str] = []
    if not data_root.is_dir():
        return [f"Missing data directory: {data_root}"]
    if not metadata_root.is_dir():
        return [f"Missing metadata directory: {metadata_root}"]

    expected: set[Path] = {
        _collection_metadata_path(directory, data_root, metadata_root)
        for directory in _iter_data_directories(data_root)
    }
    expected.update(
        _metadata_path_for_file(path, data_root, metadata_root)
        for path in _iter_data_files(data_root)
    )

    required = {
        "$schema",
        "metadata_profile",
        "identifier",
        "resource_type",
        "title",
        "abstract",
        "language",
        "responsible_parties",
        "spatial",
        "temporal",
        "lineage",
        "quality",
        "rights",
        "links",
        "metadata_generation",
    }
    for path in sorted(expected):
        if not path.exists():
            errors.append(f"Missing metadata record: {path.relative_to(root)}")
            continue
        payload = _load_json(path, None)
        if not isinstance(payload, dict):
            errors.append(f"Invalid JSON object: {path.relative_to(root)}")
            continue
        missing = sorted(required - payload.keys())
        if missing:
            errors.append(f"{path.relative_to(root)} lacks: {', '.join(missing)}")
        distribution = payload.get("distribution")
        if not isinstance(distribution, dict):
            continue
        resource_path = distribution.get("resource_path")
        if not isinstance(resource_path, str) or not resource_path.startswith("data/"):
            errors.append(f"Invalid resource_path in {path.relative_to(root)}")
            continue
        resource = root / resource_path
        if not resource.is_file():
            errors.append(f"Metadata points to missing resource: {resource_path}")
            continue
        checksum = distribution.get("checksum")
        if verify_checksums and isinstance(checksum, dict) and checksum.get("algorithm") == "SHA-256":
            if checksum.get("value") != _sha256(resource):
                errors.append(f"Checksum mismatch: {resource_path}")

    for path in metadata_root.rglob("*.json"):
        if _is_generated_record(path) and path not in expected:
            errors.append(f"Orphan generated metadata record: {path.relative_to(root)}")
    return errors


def _build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--node-root",
        default=".",
        help="OSWM node root containing config.py and data/ (default: current directory)",
    )
    parser.add_argument(
        "--no-checksums",
        action="store_true",
        help="Skip SHA-256 generation for a faster local preview",
    )
    parser.add_argument(
        "--validate-only",
        action="store_true",
        help="Validate the existing metadata tree without regenerating it",
    )
    parser.add_argument(
        "--verify-checksums",
        action="store_true",
        help="Recalculate and verify all recorded SHA-256 checksums",
    )
    return parser


def main(argv: list[str] | None = None) -> int:
    args = _build_parser().parse_args(argv)
    if args.validate_only:
        errors = validate_metadata_tree(args.node_root, verify_checksums=args.verify_checksums)
        if errors:
            print("Metadata validation failed:")
            for error in errors:
                print(f"- {error}")
            return 1
        print("Metadata validation succeeded.")
        return 0

    summary = generate_metadata(
        args.node_root,
        calculate_checksums=not args.no_checksums,
        clean_stale=True,
    )
    print(json.dumps(summary, indent=2, ensure_ascii=False))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
