from pathlib import Path
import subprocess
import sys

import pytest

from runtime_assets import publish_runtime
from runtime_validation import validate_runtime

ROOT = Path(__file__).resolve().parents[1]


def put(root, path, content="fixture"):
    target = root / path
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(content)


def test_dashboard_generator_emits_resolvable_assets_at_both_depths(tmp_path):
    # Load the real HTML emitters without importing data-acquisition globals.
    import ast
    from branding import branding_asset_url
    source = ROOT / "dashboard/statistics_funcs.py"
    names = {"get_dashboard_global_insertions", "get_dashboard_main_page_insertions"}
    tree = ast.parse(source.read_text())
    tree.body = [n for n in tree.body if isinstance(n, ast.FunctionDef) and n.name in names]
    namespace = {"branding_asset_url": branding_asset_url}
    exec(compile(tree, str(source), "exec"), namespace)
    publish_runtime(tmp_path, ROOT)
    # Isolate dashboard outputs from unrelated routing data dependencies.
    import shutil
    shutil.rmtree(tmp_path / "oswm_runtime/routing")
    shutil.rmtree(tmp_path / "oswm_runtime/hazard_analysis")
    for depth, path in [(1, "statistics/index.html"), (2, "statistics/sidewalks/chart.html")]:
        html = namespace["get_dashboard_global_insertions"](depth)["<head>"]
        if depth == 1:
            html += namespace["get_dashboard_main_page_insertions"]()["<body>"]
        put(tmp_path, path, html)
    assert validate_runtime(tmp_path) == []


def test_real_webmap_and_transitive_runtime_dependencies(tmp_path):
    publish_runtime(tmp_path, ROOT)
    put(tmp_path, "map.html", (ROOT / "webmap/webmap_base.html").read_text())
    put(tmp_path, "index.html", "<html></html>")
    # These are data products, not runtime code; the literal runtime URLs must
    # resolve without a build engine in the published tree.
    put(tmp_path, "data/basemaps/light.pmtiles")
    put(tmp_path, "data/boundaries/polygon.geojson", "{}")
    (tmp_path / "data/routing").mkdir()
    (tmp_path / "data/hazard_analysis").mkdir()
    assert not (tmp_path / "oswm_codebase").exists()
    assert validate_runtime(tmp_path) == []

    (tmp_path / "oswm_runtime/webmap/theme_charts/theme_chart_stats.js").unlink()
    errors = validate_runtime(tmp_path)
    assert any(e["url"] == "./theme_chart_stats.js" for e in errors)


@pytest.mark.parametrize("reference", [
    '<script type="module">import { Legend } from "./oswm_codebase/webmap/legend.js";</script>',
    '<script type="module">import("./oswm_codebase/webmap/legend.js");</script>',
    '<link rel="stylesheet" href="oswm_codebase/assets/stats.css">',
])
def test_build_checkout_cannot_hide_legacy_dependency(tmp_path, reference):
    put(tmp_path, "map.html", reference)
    put(tmp_path, "oswm_codebase/webmap/legend.js")
    put(tmp_path, "oswm_codebase/assets/stats.css")
    errors = validate_runtime(tmp_path)
    assert len(errors) == 1
    assert errors[0]["reason"] == "legacy build-engine dependency"
    result = subprocess.run([sys.executable, str(ROOT / "runtime_validation.py"), "--root", str(tmp_path)], capture_output=True)
    assert result.returncode == 1


def test_nested_html_css_and_module_resolution(tmp_path):
    put(tmp_path, "statistics/sidewalks/chart.html", '''
    <!-- Generated by oswm_codebase/dashboard/statistics_generation.py -->
    <link rel="stylesheet" href="../../oswm_runtime/assets/style.css">
    <img src="../../oswm_runtime/assets/logo.png">
    <script src="../../oswm_runtime/assets/chart.js"></script>
    <script>import "https://cdn.example/library.js";
    const blob = URL.createObjectURL(blobData);</script>
    ''')
    put(tmp_path, "oswm_runtime/assets/style.css", 'body { background: url("logo.png") }')
    put(tmp_path, "oswm_runtime/assets/logo.png")
    put(tmp_path, "oswm_runtime/assets/chart.js", 'export { x } from "./helper.js";')
    put(tmp_path, "oswm_runtime/assets/helper.js", "export const x = 1;")
    assert validate_runtime(tmp_path) == []
    (tmp_path / "oswm_runtime/assets/logo.png").unlink()
    errors = validate_runtime(tmp_path)
    assert len(errors) == 2
    assert {e["reason"] for e in errors} == {"missing local dependency"}


def test_every_publishing_build_mode_runs_guard_before_staging():
    import yaml
    workflow = yaml.safe_load((ROOT / ".github/workflows/node_build.yml").read_text())
    steps = workflow["jobs"]["build"]["steps"]
    guard = next(i for i, s in enumerate(steps) if "runtime_validation.py" in s.get("run", ""))
    staging = next(i for i, s in enumerate(steps) if s.get("name") == "Stage declared products")
    assert steps[guard]["if"] == "inputs.mode != 'special'"
    assert guard < staging
