from webmap_lib import *
import argparse

# create a --development flag:
parser = argparse.ArgumentParser()
parser.add_argument("--development", action="store_true")
args = parser.parse_args()

in_dev = args.development

# first, reading the parameters
params = read_json(webmap_params_original_path)

# then override and fill in with the stuff:
params["data_layers"] = MAP_DATA_LAYERS

# the layers that by type:
params["layer_types"] = layer_type_groups

# boundaries:
params["bounds"] = get_boundaries_bbox()

# updating the node's url:
params["node_url"] = node_homepage_url

params["snapshot"] = {
    "schema_version": 1,
    "node_name": CITY_NAME,
    "summary_url": snapshot_summary_path,
    "default_scope": "viewport",
    "themes": get_snapshot_themes(),
}

# # generating the "sources" and layernames:
params.update(get_sources(only_urls=True))


# very temporary:
# params['sources'] = MAP_SOURCES

params["styles"] = {
    "footway_categories": create_base_style(),
    "crossings_and_kerbs": create_crossings_kerbs_style(),
}

# adding the simple styles:
for attribute in SNAPSHOT_INTEREST_ATTRIBUTES:
    color_dict = get_color_dict(
        attribute,
        SNAPSHOT_ATTRIBUTE_LAYERS.get(attribute, "sidewalks"),
    )
    # color_schema = create_maplibre_color_schema(
    #     color_dict, attribute, different_else_color.get(attribute, "gray")
    # )

    params["styles"][attribute] = create_simple_map_style(
        name=SNAPSHOT_INTEREST_ATTRIBUTES[attribute],
        # color_schema=color_schema,
        color_dict=color_dict,
        attribute_name=attribute,
        else_color=SNAPSHOT_ELSE_COLORS.get(attribute, "gray"),
    )

# Now the numerical styles:
for fieldname in numeric_themes:
    params["styles"][fieldname] = create_simple_numeric_style(
        attribute_name=fieldname, sources=MAP_SOURCES, **numeric_themes[fieldname]
    )

# reading the base html
webmap_html = file_as_string(webmap_base_path)

# doing other stuff like insertions and nasty things (TODO):

# Extract legend HTML fragments for the native webmap legend control.
# Each style-creation function stores a __legend_html__ key in the style dict;
# we pull them out into their own top-level dict and remove the temporary key
# so the style JSON stays valid for MapLibre.
params["legend_fragments"] = {}
for key in list(params["styles"].keys()):
    legend_html = params["styles"][key].pop("__legend_html__", None)
    if legend_html:
        params["legend_fragments"][key] = legend_html

# finally generate the files:
warning_comment = """<!--
  Generated automatically by oswm_codebase/webmap/create_webmap_new.py
  Do not edit this file directly.
-->\n"""
str_to_file(warning_comment + webmap_html, webmap_path)
dump_json(params, webmap_params_path)

# if we are in dev mode, also dump the original params:
if in_dev:
    dump_json(params, webmap_params_original_path)
